kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/is2ei/drone-typetalk-test

steps:
- name: test
  image: golang
  commands:
  - go test ./...

steps:
- name: typetalk
  image: is2ei/drone-typetalk
  when:
    status: [ success, failure ]
  settings:
    typetalk_token:
      from_secret: typetalk_token
    topic_id:
      from_secret: topic_id
    template: >
      ---BUILD---

      [DRONE_BUILD_NUMBER] {{.Build.Number}}

      [DRONE_BUILD_STATUS] {{.Build.Status}}

      [DRONE_BUILD_EVENT] {{.Build.Event}}

      [DRONE_BUILD_LINK] {{.Build.Link}}

      ---REPO---

      [DRONE_REPO] {{.Repo.FullName}}

      [DRONE_REPO_OWNER] {{.Repo.Owner}}

      [DRONE_REPO_NAME] {{.Repo.Name}}

      [DRONE_REPO_BRANCH] {{.Repo.Branch}}

      [DRONE_REPO_LINK] {{.Repo.Link}}

      [DRONE_REPO_NAMESPACE] {{.Repo.NameSpace}}

      [DRONE_REPO_PRIVATE] {{.Repo.Private}}

      [DRONE_REPO_SCM] {{.Repo.SCM}}

      --COMMIT---

      [DRONE_COMMIT_SHA] {{.Commit.SHA}}

      [DRONE_COMMIT_REF] {{.Commit.Ref}}
