kind: pipeline
name: test_template

workspace:
  base: /go
  path: src/github.com/is2ei/drone-typetalk-test

steps:
- name: test
  image: golang
  commands:
  - go test ./...

steps:
- name: typetalk
  image: is2ei/drone-typetalk
  when:
    status: [ success, failure ]
  settings:
    typetalk_token:
      from_secret: typetalk_token
    topic_id:
      from_secret: topic_id
    template: >
      :wrench: test template all variables :wrench:

      ```

      ---DRONE---

      [DRONE] {{drone.isDrone}}

      [DRONE_MACHINE] {{drone.hostname}}

      [DRONE_REMOTE_URL] {{drone.hostname}}

      ---SYSTEM---

      [DRONE_SYSTEM_HOST] {{system.host}}

      [DRONE_SYSTEM_HOSTNAME] {{system.hostname}}

      [DRONE_SYSTEM_VERSION] {{system.version}}

      ---RUNNER---

      [DRONE_RUNNER_HOST] {{runner.host}}

      [DRONE_RUNNER_HOSTNAME] {{runner.hostname}}

      [DRONE_RUNNER_PLATFORM] {{runner.platform}}

      [DRONE_RUNNER_LABEL] {{runner.label}}

      ---GIT---

      [DRONE_GIT_HTTP_URL] {{git.HTTPURL}}

      [DRONE_GIT_SSH_URL] {{git.SSHURL}}

      ---REPO---

      [DRONE_REPO] {{repo.fullName}}

      [DRONE_REPO_OWNER] {{repo.owner}}

      [DRONE_REPO_NAME] {{repo.name}}

      [DRONE_REPO_BRANCH] {{repo.branch}}

      [DRONE_REPO_LINK] {{repo.link}}

      [DRONE_REPO_NAMESPACE] {{repo.nameSpace}}

      [DRONE_REPO_PRIVATE] {{repo.private}}

      [DRONE_REPO_SCM] {{repo.SCM}}

      ---BUILD---

      [DRONE_BRANCH] {{build.branch}}

      [DRONE_BUILD_CREATED] {{build.created}}

      [DRONE_BUILD_EVENT] {{build.event}}

      [DRONE_BUILD_NUMBER] {{build.number}}

      [DRONE_BUILD_STARTED] {{build.started}}

      [DRONE_BUILD_STATUS] {{build.status}}

      [DRONE_BUILD_LINK] {{build.link}}

      [DRONE_PULL_REQUEST] {{build.pullRequest}}

      [DRONE_SOURCE_BRANCH] {{build.sourceBranch}}

      [DRONE_TARGET_BRANCH] {{build.targetBranch}}

      [DRONE_TAG] {{build.tag}}

      [DRONE_DEPLOY_TO] {{build.deployTo}}

      --COMMIT---

      [DRONE_COMMIT] {{commit.commit}}

      [DRONE_COMMIT_MESSAGE] {{commit.message}}

      [DRONE_COMMIT_AFTER] {{commit.after}}

      [DRONE_COMMIT_AUTHOR] {{commit.author}}

      [DRONE_COMMIT_AUTHOR_AVATAR] {{commit.authorAvatar}}

      [DRONE_COMMIT_AUTHOR_EMAIL] {{commit.authorEmail}}

      [DRONE_COMMIT_AUTHOR_NAME] {{commit.authorName}}

      [DRONE_COMMIT_BEFORE] {{commit.before}}

      [DRONE_COMMIT_BRANCH] {{commit.branch}}

      [DRONE_COMMIT_LINK] {{commit.link}}

      [DRONE_COMMIT_SHA] {{commit.SHA}}

      [DRONE_COMMIT_REF] {{commit.ref}}

      ---JOB---

      [DRONE_JOB_STARTED] {{job.started}}

      ```
---
kind: pipeline
name: test_template_raw

workspace:
  base: /go
  path: src/github.com/is2ei/drone-typetalk-test

steps:
- name: test
  image: golang
  commands:
  - go test ./...

steps:
- name: typetalk
  image: is2ei/drone-typetalk
  when:
    status: [ success, failure ]
  settings:
    typetalk_token:
      from_secret: typetalk_token
    topic_id:
      from_secret: topic_id
    template_raw: >
      :wrench: test template_raw all variables :wrench:

      ```

      ---DRONE---

      [DRONE] {{.Drone.IsDrone}}

      [DRONE_MACHINE] {{.Drone.Hostname}}

      [DRONE_REMOTE_URL] {{.Drone.Hostname}}

      ---SYSTEM---

      [DRONE_SYSTEM_HOST] {{.System.Host}}

      [DRONE_SYSTEM_HOSTNAME] {{.System.Hostname}}

      [DRONE_SYSTEM_VERSION] {{.System.Version}}

      ---RUNNER---

      [DRONE_RUNNER_HOST] {{.Runner.Host}}

      [DRONE_RUNNER_HOSTNAME] {{.Runner.Hostname}}

      [DRONE_RUNNER_PLATFORM] {{.Runner.Platform}}

      [DRONE_RUNNER_LABEL] {{.Runner.Label}}

      ---GIT---

      [DRONE_GIT_HTTP_URL] {{.Git.HTTPURL}}

      [DRONE_GIT_SSH_URL] {{.Git.SSHURL}}

      ---REPO---

      [DRONE_REPO] {{.Repo.FullName}}

      [DRONE_REPO_OWNER] {{.Repo.Owner}}

      [DRONE_REPO_NAME] {{.Repo.Name}}

      [DRONE_REPO_BRANCH] {{.Repo.Branch}}

      [DRONE_REPO_LINK] {{.Repo.Link}}

      [DRONE_REPO_NAMESPACE] {{.Repo.NameSpace}}

      [DRONE_REPO_PRIVATE] {{.Repo.Private}}

      [DRONE_REPO_SCM] {{.Repo.SCM}}

      ---BUILD---

      [DRONE_BRANCH] {{.Build.Branch}}

      [DRONE_BUILD_CREATED] {{.Build.Created}}

      [DRONE_BUILD_EVENT] {{.Build.Event}}

      [DRONE_BUILD_NUMBER] {{.Build.Number}}

      [DRONE_BUILD_STARTED] {{.Build.Started}}

      [DRONE_BUILD_STATUS] {{.Build.Status}}

      [DRONE_BUILD_LINK] {{.Build.Link}}

      [DRONE_PULL_REQUEST] {{.Build.PullRequest}}

      [DRONE_SOURCE_BRANCH] {{.Build.SourceBranch}}

      [DRONE_TARGET_BRANCH] {{.Build.TargetBranch}}

      [DRONE_TAG] {{.Build.Tag}}

      [DRONE_DEPLOY_TO] {{.Build.DeployTo}}

      --COMMIT---

      [DRONE_COMMIT] {{.Commit.Commit}}

      [DRONE_COMMIT_MESSAGE] {{.Commit.Message}}

      [DRONE_COMMIT_AFTER] {{.Commit.After}}

      [DRONE_COMMIT_AUTHOR] {{.Commit.Author}}

      [DRONE_COMMIT_AUTHOR_AVATAR] {{.Commit.AuthorAvatar}}

      [DRONE_COMMIT_AUTHOR_EMAIL] {{.Commit.AuthorEmail}}

      [DRONE_COMMIT_AUTHOR_NAME] {{.Commit.AuthorName}}

      [DRONE_COMMIT_BEFORE] {{.Commit.Before}}

      [DRONE_COMMIT_BRANCH] {{.Commit.Branch}}

      [DRONE_COMMIT_LINK] {{.Commit.Link}}

      [DRONE_COMMIT_SHA] {{.Commit.SHA}}

      [DRONE_COMMIT_REF] {{.Commit.Ref}}

      ---JOB---

      [DRONE_JOB_STARTED] {{.Job.Started}}

      ```