kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/is2ei/drone-typetalk-test

steps:
- name: test
  image: golang
  commands:
  - go test ./...

steps:
- name: typetalk
  image: is2ei/drone-typetalk
  when:
    status: [ success, failure ]
  settings:
    typetalk_token:
      from_secret: typetalk_token
    topic_id:
      from_secret: topic_id
    template_raw: >
      ---DRONE---

      [DRONE] {{.Drone.IsDrone}}

      [DRONE_BRANCH] {{.Drone.Branch}}

      [DRONE_MACHINE] {{.Drone.Hostname}}

      [DRONE_REMOTE_URL] {{.Drone.Hostname}}

      ---GIT---

      [DRONE_GIT_HTTP_URL] {{.Git.HTTPURL}}

      [DRONE_GIT_SSH_URL] {{.Git.SSHURL}}

      ---REPO---

      [DRONE_REPO] {{.Repo.FullName}}

      [DRONE_REPO_OWNER] {{.Repo.Owner}}

      [DRONE_REPO_NAME] {{.Repo.Name}}

      [DRONE_REPO_BRANCH] {{.Repo.Branch}}

      [DRONE_REPO_LINK] {{.Repo.Link}}

      [DRONE_REPO_NAMESPACE] {{.Repo.NameSpace}}

      [DRONE_REPO_PRIVATE] {{.Repo.Private}}

      [DRONE_REPO_SCM] {{.Repo.SCM}}

      ---BUILD---

      [DRONE_BUILD_CREATED] {{.Build.Created}}

      [DRONE_BUILD_EVENT] {{.Build.Event}}

      [DRONE_BUILD_NUMBER] {{.Build.Number}}

      [DRONE_BUILD_STARTED] {{.Build.Started}}

      [DRONE_BUILD_STATUS] {{.Build.Status}}

      [DRONE_BUILD_LINK] {{.Build.Link}}

      [DRONE_PULL_REQUEST] {{.Build.PullRequest}}

      --COMMIT---

      [DRONE_COMMIT] {{.Commit.Commit}}

      [DRONE_COMMIT_MESSAGE] {{.Commit.Message}}

      [DRONE_COMMIT_AFTER] {{.Commit.After}}

      [DRONE_COMMIT_AUTHOR] {{.Commit.Author}}

      [DRONE_COMMIT_AUTHOR_AVATAR] {{.Commit.AuthorAvatar}}

      [DRONE_COMMIT_AUTHOR_EMAIL] {{.Commit.AuthorEmail}}

      [DRONE_COMMIT_AUTHOR_NAME] {{.Commit.AuthorName}}

      [DRONE_COMMIT_BEFORE] {{.Commit.Before}}

      [DRONE_COMMIT_BRANCH] {{.Commit.Branch}}

      [DRONE_COMMIT_LINK] {{.Commit.Link}}

      [DRONE_COMMIT_SHA] {{.Commit.SHA}}

      [DRONE_COMMIT_REF] {{.Commit.Ref}}
